@echo off
echo Reinstalling Tailwind CSS with compatible versions...

echo Removing old packages...
call npm uninstall tailwindcss postcss autoprefixer @tailwindcss/postcss @tailwindcss/typography

echo Installing compatible versions...
call npm install -D tailwindcss@^3.3.0 postcss@^8.4.31 autoprefixer@^10.4.16

echo Restarting dev server...
echo Please run: npm run dev
pause